AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/generators/allow_me/templates/migration/*.rb'
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

